### ISSUE TITLE
Info.plist Privacy Properties In iOS 10

### ISSUE THREAD

**Issue by prin53** [BruelAndKjaer/Chafu#14]
Since iOS 10 we have to declare Usage Description keys in `info.plist`

`<key>NSPhotoLibraryUsageDescription</key>`
`<string>Text</string>`
`<key>NSCameraUsageDescription</key>`
`<string>Text</string>`
`<key>NSCameraUsageDescription</key>`
`<string>Text</string>`
`<key> NSMicrophoneUsageDescription </key>`
`<string>Text</string>`

[NSPhotoLibraryUsageDescription](https://developer.apple.com/library/prerelease/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW17)
[NSCameraUsageDescription](NSPhotoLibraryUsageDescription)
[NSMicrophoneUsageDescription](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW25)

I think this should be added to the `README.md`.

**Comment by Cheesebaron** [comment]
Will look at that. Thank you.

**Comment by Cheesebaron** [comment]
I've added this to the README, thanks for reporting.
